In [0]:
import numpy as np


In [7]:
A = np.array([[5, 1], [3, 3]])
A

array([[5, 1],
       [3, 3]])

In [0]:
diag = np.linalg.eig(A)[0]

In [13]:
np.diag(diag)

array([[6., 0.],
       [0., 2.]])

In [0]:
V = np.linalg.eig(A)[1:]

In [0]:
V = np.array(V)

In [25]:
V

array([[[ 0.70710678, -0.31622777],
        [ 0.70710678,  0.9486833 ]]])

In [26]:
V_inv = np.linalg.inv(V)
V_inv

array([[[ 1.06066017,  0.35355339],
        [-0.79056942,  0.79056942]]])

In [0]:
lambdas = np.diag(diag)

In [0]:
decomp = V.dot(lambdas).dot(V_inv)

In [29]:
decomp

array([[[[5., 1.]],

        [[3., 3.]]]])