Matrix Multiplication




One of the most important operations involving matrices is multiplication of twomatrices. The matrix product of matrices A and B is a third matrix C. Inorder for this product to be defined,A must have the same number of columns as B has rows. If A is of shape m × n andB is of shape n × p, then Ci s of shape m × p. We can write the matrix product just by placing two or more matrices together, for example,

**C = AB.**

>$ C_{i,j} =\sum_{k} A_{i,k}.B_{k,j} $

The standard product of two matrices is called the element-wise product or the Hadamard product denoted by

>$ C = A \odot B$

Multiplying a Matrix with a vector


\begin{align*} &\begin{bmatrix} A_{1,1} & A_{1,2} \\\\ A_{2,1} & A_{2,2} \\\\ A_{3,1} & A_{3,2} \end{bmatrix}\times \begin{bmatrix} B_{1,1} \\\\ B_{2,1} \end{bmatrix}=\\\\ &\begin{bmatrix} A_{1,1}B_{1,1} + A_{1,2}B_{2,1} \\\\ A_{2,1}B_{1,1} + A_{2,2}B_{2,1} \\\\ A_{3,1}B_{1,1} + A_{3,2}B_{2,1} \end{bmatrix} \end{align*}

In [2]:
import numpy as np
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
B = np.array([[2], [4]])
B

array([[2],
       [4]])

In [4]:
C = np.dot(A, B)
C

array([[10],
       [22],
       [34]])

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
B = np.array([[2, 7], [1, 2], [3, 6]])
B

array([[2, 7],
       [1, 2],
       [3, 6]])

In [9]:
A.dot(B)

array([[ 13,  29],
       [ 31,  74],
       [ 49, 119],
       [ 67, 164]])

**Matrices mutliplication is distributive**
>$A(B+C)=AB+AC$

>${A}=\begin{bmatrix} 2 & 3 \\\\ 1 & 4 \\\\ 7 & 6 \end{bmatrix}, {B}=\begin{bmatrix} 5 \\\\ 2 \end{bmatrix}, {C}=\begin{bmatrix} 4 \\\\ 3 \end{bmatrix}$

>$\begin{align*} {A}({B}+{C})&=\begin{bmatrix} 2 & 3 \\\\ 1 & 4 \\\\ 7 & 6 \end{bmatrix}\times \left(\begin{bmatrix} 5 \\\\ 2 \end{bmatrix}+ \begin{bmatrix} 4 \\\\ 3 \end{bmatrix}\right)= \begin{bmatrix} 2 & 3 \\\\ 1 & 4 \\\\ 7 & 6 \end{bmatrix}\times \begin{bmatrix} 9 \\\\ 5 \end{bmatrix}\\\\ &= \begin{bmatrix} 2 \times 9 + 3 \times 5 \\\\ 1 \times 9 + 4 \times 5 \\\\ 7 \times 9 + 6 \times 5 \end{bmatrix}= \begin{bmatrix} 33 \\\\ 29 \\\\ 93 \end{bmatrix} \end{align*}$



>$\begin{align*} {A}{B}+{A}{C} &= \begin{bmatrix} 2 & 3 \\\\ 1 & 4 \\\\ 7 & 6 \end{bmatrix}\times \begin{bmatrix} 5 \\\\ 2 \end{bmatrix}+ \begin{bmatrix} 2 & 3 \\\\ 1 & 4 \\\\ 7 & 6 \end{bmatrix}\times \begin{bmatrix} 4 \\\\ 3 \end{bmatrix}\\\\ &= \begin{bmatrix} 2 \times 5 + 3 \times 2 \\\\ 1 \times 5 + 4 \times 2 \\\\ 7 \times 5 + 6 \times 2 \end{bmatrix}+ \begin{bmatrix} 2 \times 4 + 3 \times 3 \\\\ 1 \times 4 + 4 \times 3 \\\\ 7 \times 4 + 6 \times 3 \end{bmatrix}\\\\ &= \begin{bmatrix} 16 \\\\ 13 \\\\ 47 \end{bmatrix}+ \begin{bmatrix} 17 \\\\ 16 \\\\ 46 \end{bmatrix}= \begin{bmatrix} 33 \\\\ 29 \\\\ 93 \end{bmatrix} \end{align*}$

In [10]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [11]:
B = np.array([[5], [2]])
B

array([[5],
       [2]])

In [12]:
C = np.array([[4], [3]])
C

array([[4],
       [3]])

In [13]:
D = A.dot(B+C)
D

array([[33],
       [29],
       [93]])

In [14]:
D = A.dot(B) + A.dot(C)
D

array([[33],
       [29],
       [93]])

**Matrices mutliplication is associative**


>$A(BC)=(AB)C$

In [15]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [16]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

In [17]:
D = A.dot(B.dot(C))
D

array([[100],
       [ 85],
       [287]])

In [18]:
D = (A.dot(B)).dot(C)
D

array([[100],
       [ 85],
       [287]])

**Matrix multiplication is not commutative**

>$AB≠BA$

In [19]:
A = np.array([[2, 3], [6, 5]])
A

array([[2, 3],
       [6, 5]])

In [20]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

In [21]:
AB = np.dot(A, B)
AB

array([[16, 12],
       [40, 28]])

In [23]:
BA = np.dot(B,A) #compare with above they are not the same
BA

array([[28, 30],
       [16, 16]])

**However vector products are commutative**
>$x^Ty = y^Tx$


**Simplification of the matrix product**
>$(AB)^T = B^TA^T$


**Linear System of Equations**

A vector is a point in space. But that point cannot travel along the space by linearly just by adding a scalar as a vector is a point along many axis. A matrix is used to transform a vector and also to move a vector from one place to another place. A matrix can also be represented as a linear system of equations

\begin{cases} y = 2x + 1 \\\\ y = \frac{7}{2}x +3 \end{cases}

>$A_{1,1}x_1 + A_{1,2}x_2 + A_{1,n}x_n = b_1 \\\\ A_{2,1}x_1 + A_{2,2}x_2 + A_{2,n}x_n = b_2 \\\\ \cdots \\\\ A_{m,1}x_1 + A_{m,2}x_2 + A_{m,n}x_n = b_n$


Matrices used to describe an equation 
>$Ax = b$