A **scalar** is just a single number .

A **vector** is an ordered array of numbers. Each element in the array is identifiable by it's index. The points in the array combine to give a particular location of the vector on an axis. The total number of points indicating it's dimension. Going ahead to Machine Learning, a vector is made up of a number of features such as a house vector will have features such as area, no.of bedrooms etc. These can be seen as different points along different axis in the coordinate system and together denote the house vector in space.

In [0]:
scalar = 4 #example of scalar

In [3]:
import numpy as np
vector  = np.array([1,2,34,59])
vector

array([ 1,  2, 34, 59])

A **matrix** is a 2-D array so each element is identifiedby two indices instead of just one. Each matrix has a shape to denote it's dimensions.  A matrix can also be said as an array of vectors

A **tensor** is difficult to visualize in the naked eye as a tensor as very high dimensions. In simple terms a tensor can be told as an array of matrices. They are used a lot in image processing as images especially colour images are a combination of matrices of different combinations of R,G,B

In [0]:
A = np.array([[1, 2], [3, 4], [5, 6]])

**Shape**

The shape of an array (that is to say its dimensions) tells you the number of values for each dimension. For a 2-dimensional array it will give you the number of rows and the number of columns. Let’s find the shape of our preceding 2-dimensional array A. Since A is a Numpy array (it was created with the array() function) you can access its shape with:

In [8]:
A.shape,vector.shape

((3, 2), (4,))

# **Transposition**

One important operation on matrices is thetranspose. The transpose of amatrix is the mirror image of the matrix across a diagonal line, called themaindiagonal, running down and to the right, starting from its upper left corner. Seefigure 2.1 for a graphical depiction of this operation. We denote the transpose of a matrix A as 

>$A^T$

>$(A^T)_{i,j}= A_{j,i}$

In [13]:
A.T.shape,A.shape

((2, 3), (3, 2))

In [14]:
A,A.T

(array([[1, 2],
        [3, 4],
        [5, 6]]), array([[1, 3, 5],
        [2, 4, 6]]))

In [15]:
#Addition of matrices
B = np.array([[2, 5], [7, 4], [4, 3]])
B

array([[2, 5],
       [7, 4],
       [4, 3]])

In [16]:
C = A + B #  two matrices can only be added if they have the same shape
C

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

In [17]:
#Add a scalar to a matrix. This means the scalar will be added to every element in the matrix
D = C + 5
D

array([[ 8, 12],
       [15, 13],
       [14, 14]])

**Broadcasting**




\begin{bmatrix} A_{1,1} & A_{1,2} \\\\ A_{2,1} & A_{2,2} \\\\ A_{3,1} & A_{3,2} \end{bmatrix}+ \begin{bmatrix} B_{1,1} \\\\ B_{2,1} \\\\ B_{3,1} \end{bmatrix}

Gives



\begin{bmatrix} A_{1,1} & A_{1,2} \\\\ A_{2,1} & A_{2,2} \\\\ A_{3,1} & A_{3,2} \end{bmatrix} + \begin{bmatrix} B_{1,1} & B_{1,1} \\\\ B_{2,1} & B_{2,1} \\\\ B_{3,1} & B_{3,1} \end{bmatrix}= \begin{bmatrix} A_{1,1} + B_{1,1} & A_{1,2} + B_{1,1} \\\\ A_{2,1} + B_{2,1} & A_{2,2} + B_{2,1} \\\\ A_{3,1} + B_{3,1} & A_{3,2} + B_{3,1} \end{bmatrix}

In [18]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
B = np.array([[2], [4], [6]])
B

array([[2],
       [4],
       [6]])

In [20]:
# Broadcasting
C=A+B
C

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])